services:
  - type: web
    name: myzapp-bot
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: USE_SERVER
        value: true
      - key: SESSION
        sync: false   # Indique au CLI de vous demander votre chaîne SESSION de manière sécurisée lors du premier déploiement
      - key: GEMINI_API_KEY
        value: AQ.Ab8RN6JaHx-U8ogNSTkPT2VmO9PvV9N9SqOzBhzmiFmffdNrtw
      - key: DATABASE_URL
        value: postgresql://joinvesting_db_user:nG3RMqgXwtnKf9zp5juQiESZB9N6VbJp@dpg-da10ckpt0dsc73ao2190-a.singapore-postgres.render.com/joinvesting_db?sslmode=require
